#To start the server from this docker-compose file you can run the command "docker-compose up"
#Configure the location of the configuration file and the data folder
#The connection to mysql should match the name of the service in this case "mysqldb"
version: "2.4"
services:
  mangosd:
    build:
      context: ..
      dockerfile: dockercontainer/Dockerfile-mangosd
    depends_on:
      - mysqldb
    restart: always
    ports:
      - "8085:8085"
    volumes:
#      - ./your/location/config:/config
      - ../../etc:/mangos/etc
      - ../../data:/mangos/data

  realmd:
    build:
      context: ..
      dockerfile: dockercontainer/Dockerfile-realmd
    depends_on:
      - mysqldb
    restart: always
    ports:
      - "3724:3724"
    volumes:
#      - ./your/location/config:/config
      - ../../etc:/mangos/etc

  mysqldb:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always
    environment:
      - MYSQL_USER=mangos
      - MYSQL_PASSWORD=mangos
      - MYSQL_ROOT_PASSWORD=mangos
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - ../../dbdata:/var/lib/mysql
